# Generated by Django 3.1.6 on 2021-02-05 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('car_make', models.CharField(help_text='Make of a car', max_length=255, verbose_name='Make')),
                ('car_model', models.CharField(help_text='Model of a car', max_length=255, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rating_stars', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating of a car from 1 to 5', verbose_name='Stars')),
                ('rating_car', models.ForeignKey(help_text='Car model that is rated by a user', on_delete=django.db.models.deletion.CASCADE, related_name='car_rating', to='cars.car', verbose_name='Car rating')),
                ('rating_user', models.ForeignKey(help_text='User that rated a car', on_delete=django.db.models.deletion.CASCADE, related_name='car_rating', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Car rating',
                'verbose_name_plural': 'Car ratings',
                'unique_together': {('rating_user', 'rating_car')},
            },
        ),
    ]
