from .test_get_all_cars_with_avg_rating import GetAllCarsWithAvgRatingSelectorTest
from .test_get_all_cars_popularity import GetAllCarsPopularityTest
from .test_get_models_for_make import GetModelsForMakeTest
